### ISSUE TITLE
[bug] installation issue

### ISSUE THREAD

**Issue by redet-G** [gonenlab/AuthWP#1]
Default installation error on
```Web Server Info:          			Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
PHP Version:              			7.4.19
Wordpress:                                       6.1
mediawiki:                                        1.38.4
```
See the full log here @CiaranG @hattne 
```
MediaWiki internal error.

Original exception: [1c4a21deba54c5b35e213d50] /wordpress/mediawiki/index.php/Main_Page Error: Call to undefined method User::getCanonicalName()
Backtrace:
from C:\laragon\www\wordpress\mediawiki\extensions\AuthWP\includes\AuthWPSessionProvider.php(85)
#0 C:\laragon\www\wordpress\mediawiki\includes\session\SessionManager.php(525): AuthWPSessionProvider->provideSessionInfo(WebRequest)
#1 C:\laragon\www\wordpress\mediawiki\includes\session\SessionManager.php(247): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#2 C:\laragon\www\wordpress\mediawiki\includes\WebRequest.php(837): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#3 C:\laragon\www\wordpress\mediawiki\includes\session\SessionManager.php(168): WebRequest->getSession()
#4 C:\laragon\www\wordpress\mediawiki\includes\Setup.php(878): MediaWiki\Session\SessionManager::getGlobalSession()
#5 C:\laragon\www\wordpress\mediawiki\includes\WebStart.php(93): require_once(string)
#6 C:\laragon\www\wordpress\mediawiki\index.php(44): require(string)
#7 {main}

Exception caught inside exception handler: [1c4a21deba54c5b35e213d50] /wordpress/mediawiki/index.php/Main_Page Error: Call to undefined method User::getCanonicalName()
Backtrace:
from C:\laragon\www\wordpress\mediawiki\extensions\AuthWP\includes\AuthWPSessionProvider.php(85)
#0 C:\laragon\www\wordpress\mediawiki\includes\session\SessionManager.php(525): AuthWPSessionProvider->provideSessionInfo(WebRequest)
#1 C:\laragon\www\wordpress\mediawiki\includes\session\SessionManager.php(247): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#2 C:\laragon\www\wordpress\mediawiki\includes\WebRequest.php(837): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#3 C:\laragon\www\wordpress\mediawiki\includes\user\User.php(1058): WebRequest->getSession()
#4 C:\laragon\www\wordpress\mediawiki\includes\user\User.php(383): User->loadDefaults()
#5 C:\laragon\www\wordpress\mediawiki\includes\user\User.php(1892): User->load()
#6 C:\laragon\www\wordpress\mediawiki\includes\user\User.php(2530): User->getId()
#7 C:\laragon\www\wordpress\mediawiki\includes\user\UserOptionsManager.php(644): User->isRegistered()
#8 C:\laragon\www\wordpress\mediawiki\includes\user\UserOptionsManager.php(496): MediaWiki\User\UserOptionsManager->getCacheKey(User)
#9 C:\laragon\www\wordpress\mediawiki\includes\user\UserOptionsManager.php(147): MediaWiki\User\UserOptionsManager->loadUserOptions(User, integer)
#10 C:\laragon\www\wordpress\mediawiki\includes\context\RequestContext.php(452): MediaWiki\User\UserOptionsManager->getOption(User, string)
#11 C:\laragon\www\wordpress\mediawiki\includes\language\Message.php(384): RequestContext->getLanguage()
#12 C:\laragon\www\wordpress\mediawiki\includes\language\Message.php(1491): Message->getLanguage()
#13 C:\laragon\www\wordpress\mediawiki\includes\language\Message.php(968): Message->fetchMessage()
#14 C:\laragon\www\wordpress\mediawiki\includes\language\Message.php(1071): Message->format(string)
#15 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionRenderer.php(228): Message->text()
#16 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionRenderer.php(160): MWExceptionRenderer::msg(string, string)
#17 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML(Error)
#18 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionHandler.php(107): MWExceptionRenderer::output(Error, integer)
#19 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionHandler.php(202): MWExceptionHandler::report(Error)
#20 C:\laragon\www\wordpress\mediawiki\includes\exception\MWExceptionHandler.php(170): MWExceptionHandler::handleException(Error, string)
#21 [internal function]: MWExceptionHandler::handleUncaughtException(Error)
#22 {main}
``

**Comment by hattne** [comment]
getCanonicalName() was deprecated in MediaWiki 1.35 and finally removed in 1.38.
